- .gitignore
- README.md
- package.json
- src/cli/commands/help.ts
- src/cli/commands/interpret.ts
- src/cli/index.ts
- src/types.ts
- src/utils/readImageData.ts
- test/fixtures.ts
- test/utils.ts
- yarn.lock
Example from the updated README:
```sh
$ hmpb interpret -e election.json \
template-2020-04-15-0001.jpg \
template-2020-04-15-0002.jpg \
template-2020-04-15-0001-full-votes.jpg \
template-2020-04-15-0002-full-votes.jpg
╔═══════════════════════════════════════════════════════╤═════════════════════════════════════════╤═════════════════════════════════════════╗
║ Contest                                               │ template-2020-04-15-0001-full-votes.jpg │ template-2020-04-15-0002-full-votes.jpg ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────┼─────────────────────────────────────────╢
║ Member, U.S. Senate                                   │ Tim Smith                               │                                         ║ …
```
> feat: add CLI to interpret ballots

- src/Interpreter.ts
> use the custom qr code decoder on ballots, not just templates

- src/Interpreter.test.ts
- test/fixtures/election.json
https://github.com/votingworks/election-definitions/pull/9
> test: update election definition

- package.json
- src/Interpreter.test.ts
- src/cli/commands/interpret.ts
- test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/election.json
- test/fixtures/election-98f5203139-choctaw-general-2019/election.json
- test/regression/28lb-paper.test.ts
- yarn.lock
We want to make sure we're using the latest since recent types changes are not compatible.
> fix: update ballot encoder

- package.json
> Publish v4.0.0

- package.json
> Publish v4.0.1

- package.json
> Publish v4.1.0

- package.json
> Publish v4.1.1

- package.json
> Publish v4.2.0

- package.json
> Publish v5.1.0

- package.json
> Publish v5.1.1

- package.json
> Publish v5.1.2

- package.json
- yarn.lock
This shouldn't affect behavior at all, but opens up some new features: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html
> chore: upgrade typescript

- package.json
- yarn.lock
Mostly removes a warning from ts-jest about an incompatible jest version.
> test: update jest & related dependencies

- package.json
> Publish v5.1.5

- package.json
Includes #81, #82, #83, and #84.
> Publish v5.2.0

- package.json
> Publish v5.2.2

- package.json
> Publish v5.2.3

- package.json
> Publish v5.2.4

- src/Interpreter.test.ts
- src/Interpreter.ts
Jiggle a bit more vertically, and short-circuit minimization on a high-enough score.
> adjust target scoring

- src/Interpreter.ts
- src/cli/commands/help.ts
- src/cli/commands/interpret.ts
- src/utils/VisitedPoints.ts
- src/utils/qrcode/quirc.ts
- src/utils/qrcode/withCropping.ts
- tsconfig.json
And enable some TypeScript checks to flag problems in the future, fixing or silencing the current issues.
> fix: remove unused parameter
