- src/Interpreter.test.ts
- src/Interpreter.ts
- src/types.ts
The result still includes the normalized `votes` property with a decision made about each contest option based on the marks, but it now includes a `marks` property with all the data used to generate `votes`. This property can be used to determine whether a ballot needs human adjudication, for example.
> feat: include details about ballot marks

- src/utils/convert.ts
- src/utils/crop.test.ts
- src/utils/crop.ts
- src/utils/makeImageTransform.ts
- test/utils.ts
This makes it possible for us to crop either grayscale or RGBA images without requiring a round-trip through RGBA.
Also ensures that `writeImageFile` always calls `putImageData` with an RGBA image, since otherwise it segfaults.
> refactor: implement grayscale crop

- src/Interpreter.test.ts
- src/Interpreter.ts
- src/metadata.test.ts
- src/utils/flip.test.ts
- src/utils/flip.ts
- src/utils/makeImageTransform.ts
This should be more performant as it doesn't need to allocate a whole new image, which for a typical scanned ballot is 33MB.
> refactor: make `vh` flip operate inline

- src/Interpreter.test.ts
When this one fails, it causes jest to consume all the remaining memory on the system trying to diff two `ImageData` instances.
> test: remove problematic assertion

- src/utils/qrcode/quirc.ts
- types/node-quirc.d.ts
node-quirc will actually resolve the promise even if it finds a QR code it can't decode. This makes sense since there may be QR codes it could decode and you need a way to communicate that. The ones that error will have just an `err` property and nothing else, so we now just return the first QR code that does not have an `err` property.
> fix(quirc): handle QR code errors better

- src/utils/crop.test.ts
- src/utils/crop.ts
- test/utils.ts
This uses a technique pointed out here: https://github.com/cozmo/jsQR/issues/168#issuecomment-621520019. It should be more efficient, and has the added bonus of working with both RGBA and grayscale.
> refactor: simplify `crop`

- src/Interpreter.test.ts
- src/types.ts
- src/utils/geometry.test.ts
- src/utils/geometry.ts
- test/utils.ts
This was a classic off-by-one error. Also adds some assertions to validate the test data.
> fix: ensure rect corners are in bounds

- src/Interpreter.ts
- src/utils/flip.ts
- src/utils/grayscale.ts
- src/utils/jsfeat/diff.test.ts
- src/utils/jsfeat/diff.ts
- src/utils/makeImageTransform.ts
The comparison bounds still need to be equally-sized, but it previously assumed that the `base` and `compare` images were themselves the same sizes.
> fix: support diffing images of different widths

- src/Interpreter.test.ts
- src/Interpreter.ts
This helps clients determine which templates are still needed before ballots can be interpreted, which could be used for showing hints and progress to end users.
> feat: add `Interpreter#getMissingTemplates`

- src/Interpreter.test.ts
- src/Interpreter.ts
Before this fix, any "no" votes would be counted as "yes" votes.
> fix: ensure "no" target options are recorded as such

- src/Interpreter.test.ts
- src/cli/commands/interpret.ts
- src/hmpb/scanColumns.ts
- src/hmpb/votes.ts
- src/utils/jsfeat/drawToCanvas.ts
- src/utils/qrcode/index.ts
- src/utils/qrcode/quirc.ts
- test/fixtures.ts
Removes an unused import in `interpret.ts`.
> style: organize imports across all files

- src/Interpreter.test.ts
- src/Interpreter.ts
- src/metadata.test.ts
- test/fixtures.ts
This could be used by `module-scan` to look for QR codes ahead of time and provide the metadata and orientation information instead of making this library do it.
> feat: allow specifying whether a ballot is flipped

- src/Interpreter.test.ts
- src/Interpreter.ts
- test/fixtures.ts
- test/fixtures/election-4e31cb17d8f2f3bac574c6d2f6e22fb2528dcdf8-ballot-style-77-precinct-oaklawn-branch-library/blank-p1-metadata.json
- test/fixtures/election-4e31cb17d8f2f3bac574c6d2f6e22fb2528dcdf8-ballot-style-77-precinct-oaklawn-branch-library/blank-p2-metadata.json
- test/fixtures/election-4e31cb17d8f2f3bac574c6d2f6e22fb2528dcdf8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1-metadata.json
- test/fixtures/election-4e31cb17d8f2f3bac574c6d2f6e22fb2528dcdf8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p2-metadata.json
This change requires that an interpreter have a test mode set, and that ballots and templates to be processed match that test mode.
votingworks/vxmail#32
> fix: enforce test mode for scanned ballots

- src/Interpreter.test.ts
- src/Interpreter.ts
- src/types.ts
The marks in the output are in the coordinate space of the mapped ballot, so if we want to line them up with the image we need the mapped image.
> feat: expose mapped ballot in interpreted result

- src/Interpreter.test.ts
- src/metadata.test.ts
The only changes needed are in the tests, since the scheme, path, and host of the QR code URL are ignored.
> test: replace `vx.vote` with `ballot.page`

- src/Interpreter.test.ts
- src/Interpreter.ts
I plan to store the results of ballot interpretation in the database, and so I'll need to interpret live and test ballots using the same interpreter. I'll only add the ones that match the expected mode.
> fix: allow interpreting template even with a different test mode

- src/cli/commands/help.ts
- src/cli/commands/interpret.ts
BREAKING CHANGE. Previously the metadata would be specified as colon-separated values. This was becoming unweildy as we added more metadata values. Now we accept a JSON metadata filename.
> feat: allow passing metadata in JSON files for CLI processing

- README.md
- src/Interpreter.test.ts
- src/Interpreter.ts
- test/regression/28lb-paper.test.ts
This is not indended to carry through all the way to CVRs, but will make adjudicating marks easier.
> fix: ensure write-in options have unique ids

- package.json
- src/Interpreter.test.ts
- src/Interpreter.ts
- yarn.lock
This allows pulling the mark score vote threshold from the election definition if it is set. It also allows overriding it for the purposes of a single ballot interpretation.
> feat: better mark score vote threshold config

- src/cli/commands/interpret.ts
Ideally we'd also allow checking the QR code to read the metadata to make this check, but for now this is at least better.
> fix: do not require all templates on CLI when providing metadata

- package.json
- src/Interpreter.ts
- src/hmpb/votes.ts
- src/types.ts
- yarn.lock
This does not guarantee that we'll be able to interpret them, but if they follow the same shape as other contests we should be able to find all the options. It assumes the order of answers is either/neither/first/second.
> feat: add support for representing ms-either-neither contests

- src/hmpb/findContests.ts
We should base the expected contest width on the number of columns by default. When there are three columns, we now expect a contest box to be between 28-39% vs 20-40% previously. If only two columns are given, it'd be 45-55%. More work will likely need to be done to support two-column layouts, but this is a fairly obvious start.
> fix: be smarter about column sizes

- package.json
- src/Interpreter.test.ts
- src/utils/binarize.test.ts
- src/utils/canvas.ts
- src/utils/crop.test.ts
- src/utils/crop.ts
- src/utils/flip.test.ts
- src/utils/jsfeat/matToImageData.ts
- src/utils/outline.ts
- src/utils/qrcode/quirc.ts
- src/utils/readImageData.ts
- test/utils.ts
- yarn.lock
canvas does not support being loaded in worker threads due to it being a native dependency that was not written using a thread-compatible API. sharp, on the other hand, is thread-aware: https://github.com/lovell/sharp/issues/1558.
> refactor: replace canvas with sharp

- package.json
- src/hmpb/findContests.ts
In practice, a very tall contest box could be ~88% of the total height. Let's call it 90% just to be safe.
> fix: allow taller contests

- src/Interpreter.test.ts
- src/Interpreter.ts
- src/types.ts
When we look around the bubbles for a better fit, we previously didn't record the scored offset. Now we do.
> feat: record the scored offset

- test/utils.ts
When I switched it to use `sharp` I didn't properly create a `Buffer` from image data. Now it should work.
> test: fix `writeImageToFile` util

- src/Interpreter.test.ts
- src/Interpreter.ts
This reduces the radius that the mark score minimization algorithm can go to find a lower score. We've been seeing it start dead center, but then moving away in order to shrink the score. This is not what we want, and this is not going to fix that, but it will reduce the effect. Experimentally, a radius of 2 makes all the zero scores stay zero, but boosts the non-zero scores. In the future we may want to also "maximize" the score as well, then use both scores to determine what to do.
> fix: boost signal from actually-marked targets

- src/utils/corners.test.ts
- src/utils/corners.ts
I wasn't doing proper bounds checking on the x,y values, so in some conditions we might go beyond the bounding box looking for black pixels. In some cases, we'd even go outside the bounds of the image. Once that happens, we'd loop forever since the pixel value at such points is `undefined`, which will never equal 0.
This happened because we were looking for TWO consecutive black pixels along the edge of the bounding box in either direction. However, there only has to be ONE consecutive pixel for it to push the bounding box out. This is the case that would cause the corner finder to keep going beyond the bounding box and possibly forever.
Finding two consecutive pixels was from before I implemented backtracking, and no longer seems necessary. Once we find a single black pixel we can …
> fix: prevent infinite loop looking for corners

- src/Interpreter.test.ts
- src/Interpreter.ts
- src/hmpb/findContests.ts
- src/hmpb/findTargets.ts
- src/hmpb/shapes.test.ts
- src/hmpb/shapes.ts
- src/utils/offsets.ts
Off-by-1 errors! This has been wrong for some time, and will likely have minimal effect on scores. Still, it's important to get every little bit we can to aid alignment. Without this, the right and bottom edges of all shapes (i.e. targets and contests) are cut off by one pixel.
Fixing this also exposed another bug. We were continuing to look for contests in a column past the point we expected to see the first one as long as we saw _any_ shape by the point we expected to see a contest box. This is now fixed too.
> fix: correct shape sizes

- package.json
- src/Interpreter.ts
Building a homography requires at least three points, so we can't just use the left two corners of the single contest box on a page. In that case, use all four corners.
> fix: ensure single-contest pages scan correctly

- package.json
- src/Interpreter.ts
On 2-column pages the contests are wide enough that the skew on the right side can cause problems with the left side lining up, even though we got the left corners lined up. This has led to spurious overvotes on the tall+wide either-neither contest in the upcoming general election in MS. This change was tested with 3798 scans, and it went from 91 either-neither overvotes to 2 either-neither overvotes.
> fix: use all four contest corners on 2-column pages

- package.json
- yarn.lock
Without this, using the latest ballot-encoder would complain about conflicting types, since the latest has mostly readonly properties and the old one does not.
> fix(types): upgrade ballot-encoder
